<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260604142024 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE conversion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, file_name VARCHAR(255) NOT NULL, file_size INT NOT NULL, table_name VARCHAR(255) NOT NULL, dialect VARCHAR(50) NOT NULL, columns JSON NOT NULL, inferred_types JSON NOT NULL, exclusions JSON NOT NULL, primary_key VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BD912744A76ED395 ON conversion (user_id)');
        $this->addSql('CREATE TABLE conversion_jobs (id UUID NOT NULL, status VARCHAR(20) NOT NULL, conversion_type VARCHAR(50) NOT NULL, source_format VARCHAR(10) NOT NULL, target_format VARCHAR(10) NOT NULL, options JSON NOT NULL, error_message TEXT DEFAULT NULL, progress_pct SMALLINT NOT NULL, started_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, finished_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, user_id UUID NOT NULL, template_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C89A76E2A76ED395 ON conversion_jobs (user_id)');
        $this->addSql('CREATE INDEX IDX_C89A76E25DA0FB8 ON conversion_jobs (template_id)');
        $this->addSql('CREATE TABLE files (id UUID NOT NULL, role VARCHAR(10) NOT NULL, original_name VARCHAR(255) NOT NULL, storage_key VARCHAR(500) NOT NULL, mime_type VARCHAR(100) NOT NULL, size_bytes BIGINT NOT NULL, checksum VARCHAR(64) NOT NULL, expires_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, user_id UUID NOT NULL, job_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6354059111795A5 ON files (storage_key)');
        $this->addSql('CREATE INDEX IDX_6354059A76ED395 ON files (user_id)');
        $this->addSql('CREATE INDEX IDX_6354059BE04EA9 ON files (job_id)');
        $this->addSql('CREATE TABLE media_objects (id UUID NOT NULL, role VARCHAR(15) DEFAULT \'avatar\' NOT NULL, file_name VARCHAR(255) NOT NULL, file_path_url VARCHAR(500) NOT NULL, mime_type VARCHAR(100) NOT NULL, size_bytes BIGINT DEFAULT NULL, checksum VARCHAR(64) DEFAULT NULL, expires_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, user_id UUID NOT NULL, job_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D3CD4ABAF44B7626 ON media_objects (file_path_url)');
        $this->addSql('CREATE INDEX IDX_D3CD4ABAA76ED395 ON media_objects (user_id)');
        $this->addSql('CREATE INDEX IDX_D3CD4ABABE04EA9 ON media_objects (job_id)');
        $this->addSql('CREATE TABLE refresh_tokens (id UUID NOT NULL, token_hash VARCHAR(255) NOT NULL, device_info VARCHAR(255) DEFAULT NULL, expires_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, revoked_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9BACE7E1B3BC57DA ON refresh_tokens (token_hash)');
        $this->addSql('CREATE INDEX IDX_9BACE7E1A76ED395 ON refresh_tokens (user_id)');
        $this->addSql('CREATE INDEX idx_refresh_token_hash ON refresh_tokens (token_hash)');
        $this->addSql('CREATE TABLE templates (id UUID NOT NULL, name VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, mapping_config JSON NOT NULL, is_public BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, owner_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6F287D8E7E3C61F9 ON templates (owner_id)');
        $this->addSql('CREATE TABLE usage_stats (id UUID NOT NULL, period VARCHAR(7) NOT NULL, jobs_total INT NOT NULL, jobs_ok INT NOT NULL, jobs_failed INT NOT NULL, bytes_processed BIGINT NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DD890454A76ED395 ON usage_stats (user_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_user_period ON usage_stats (user_id, period)');
        $this->addSql('CREATE TABLE users (id UUID NOT NULL, email VARCHAR(180) NOT NULL, password_hash VARCHAR(255) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, role VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, locale VARCHAR(10) DEFAULT \'en\' NOT NULL, timezone VARCHAR(50) DEFAULT \'UTC\' NOT NULL, profile_picture VARCHAR(255) DEFAULT NULL, email_verified_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, last_login_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('ALTER TABLE conversion ADD CONSTRAINT FK_BD912744A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversion_jobs ADD CONSTRAINT FK_C89A76E2A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversion_jobs ADD CONSTRAINT FK_C89A76E25DA0FB8 FOREIGN KEY (template_id) REFERENCES templates (id)');
        $this->addSql('ALTER TABLE files ADD CONSTRAINT FK_6354059A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE files ADD CONSTRAINT FK_6354059BE04EA9 FOREIGN KEY (job_id) REFERENCES conversion_jobs (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media_objects ADD CONSTRAINT FK_D3CD4ABAA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media_objects ADD CONSTRAINT FK_D3CD4ABABE04EA9 FOREIGN KEY (job_id) REFERENCES conversion_jobs (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE refresh_tokens ADD CONSTRAINT FK_9BACE7E1A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE templates ADD CONSTRAINT FK_6F287D8E7E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE usage_stats ADD CONSTRAINT FK_DD890454A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE conversion DROP CONSTRAINT FK_BD912744A76ED395');
        $this->addSql('ALTER TABLE conversion_jobs DROP CONSTRAINT FK_C89A76E2A76ED395');
        $this->addSql('ALTER TABLE conversion_jobs DROP CONSTRAINT FK_C89A76E25DA0FB8');
        $this->addSql('ALTER TABLE files DROP CONSTRAINT FK_6354059A76ED395');
        $this->addSql('ALTER TABLE files DROP CONSTRAINT FK_6354059BE04EA9');
        $this->addSql('ALTER TABLE media_objects DROP CONSTRAINT FK_D3CD4ABAA76ED395');
        $this->addSql('ALTER TABLE media_objects DROP CONSTRAINT FK_D3CD4ABABE04EA9');
        $this->addSql('ALTER TABLE refresh_tokens DROP CONSTRAINT FK_9BACE7E1A76ED395');
        $this->addSql('ALTER TABLE templates DROP CONSTRAINT FK_6F287D8E7E3C61F9');
        $this->addSql('ALTER TABLE usage_stats DROP CONSTRAINT FK_DD890454A76ED395');
        $this->addSql('DROP TABLE conversion');
        $this->addSql('DROP TABLE conversion_jobs');
        $this->addSql('DROP TABLE files');
        $this->addSql('DROP TABLE media_objects');
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('DROP TABLE templates');
        $this->addSql('DROP TABLE usage_stats');
        $this->addSql('DROP TABLE users');
    }
}
